"""llm_toolkit_schema.namespaces.inspect — LLM output inspection payload types.

Classes
-------
InspectIssueSummary
    Value object describing a single detected issue within an inspect report.
InspectReportPayload
    ``llm.inspect.report`` — a completed inspection report generated against a
    tracing span by llm-inspect.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass(frozen=True)
class InspectIssueSummary:
    """A single detected issue within an inspect report.

    Parameters
    ----------
    issue_type:
        Category of the detected issue, e.g. ``"hallucination"``,
        ``"off_topic"``, ``"policy_violation"``, ``"factual_error"``.
    severity:
        Severity level: ``"low"``, ``"medium"``, ``"high"``, ``"critical"``.
    description:
        Human-readable description of the specific issue detected.
    """

    issue_type: str
    severity: str
    description: str

    # -----------------------------------------------------------------
    # Validation
    # -----------------------------------------------------------------

    def __post_init__(self) -> None:
        for attr in ("issue_type", "severity", "description"):
            value = getattr(self, attr)
            if not value or not isinstance(value, str):
                raise ValueError(f"InspectIssueSummary.{attr} must be a non-empty string")
        if self.severity not in frozenset({"low", "medium", "high", "critical"}):
            raise ValueError(
                f"InspectIssueSummary.severity must be low/medium/high/critical, "
                f"got {self.severity!r}"
            )

    # -----------------------------------------------------------------
    # Serialisation
    # -----------------------------------------------------------------

    def to_dict(self) -> Dict[str, Any]:
        """Return a plain dict suitable for embedding in an inspect report."""
        return {
            "issue_type": self.issue_type,
            "severity": self.severity,
            "description": self.description,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "InspectIssueSummary":
        """Reconstruct an :class:`InspectIssueSummary` from a plain dict."""
        return cls(
            issue_type=str(data["issue_type"]),
            severity=str(data["severity"]),
            description=str(data["description"]),
        )


@dataclass(frozen=True)
class InspectReportPayload:
    """Payload for ``llm.inspect.report``.

    Generated by llm-inspect after analysing the output of a tracing span.
    Consumers (dashboards, alerting systems, eval pipelines) subscribe to
    this event type to surface quality or policy issues in LLM outputs.

    Parameters
    ----------
    report_id:
        Unique identifier for this inspection report.
    span_id:
        The span identifier of the LLM call that was inspected.
    model:
        The model that produced the output being inspected,
        e.g. ``"gpt-4o"``.
    issues:
        List of :class:`InspectIssueSummary` objects describing detected
        problems.  An empty list means the report is clean.
    overall_severity:
        Rolled-up severity across all issues: ``"none"``, ``"low"``,
        ``"medium"``, ``"high"``, or ``"critical"``.
    score:
        Optional quality/compliance score in the range ``[0.0, 1.0]``
        where ``1.0`` means fully compliant and ``0.0`` means completely
        non-compliant.
    inspector_version:
        Optional version string of the llm-inspect build that generated
        this report.
    """

    report_id: str
    span_id: str
    model: str
    issues: List[InspectIssueSummary]
    overall_severity: str
    score: Optional[float] = None
    inspector_version: Optional[str] = None

    # -----------------------------------------------------------------
    # Validation
    # -----------------------------------------------------------------

    def __post_init__(self) -> None:
        for attr in ("report_id", "span_id", "model", "overall_severity"):
            value = getattr(self, attr)
            if not value or not isinstance(value, str):
                raise ValueError(f"InspectReportPayload.{attr} must be a non-empty string")
        if self.overall_severity not in frozenset(
            {"none", "low", "medium", "high", "critical"}
        ):
            raise ValueError(
                f"InspectReportPayload.overall_severity must be none/low/medium/high/critical, "
                f"got {self.overall_severity!r}"
            )
        if not isinstance(self.issues, list):
            raise TypeError("InspectReportPayload.issues must be a list")
        for item in self.issues:
            if not isinstance(item, InspectIssueSummary):
                raise TypeError(
                    "Each item in InspectReportPayload.issues must be an InspectIssueSummary"
                )
        if self.score is not None:
            if not isinstance(self.score, (int, float)) or not (0.0 <= float(self.score) <= 1.0):
                raise ValueError(
                    f"InspectReportPayload.score must be in [0.0, 1.0], got {self.score!r}"
                )
        if self.inspector_version is not None and not isinstance(self.inspector_version, str):
            raise TypeError("InspectReportPayload.inspector_version must be a string or None")

    # -----------------------------------------------------------------
    # Serialisation
    # -----------------------------------------------------------------

    def to_dict(self) -> Dict[str, Any]:
        """Return a plain dict suitable for ``Event.payload``."""
        result: Dict[str, Any] = {
            "report_id": self.report_id,
            "span_id": self.span_id,
            "model": self.model,
            "issues": [issue.to_dict() for issue in self.issues],
            "overall_severity": self.overall_severity,
        }
        if self.score is not None:
            result["score"] = self.score
        if self.inspector_version is not None:
            result["inspector_version"] = self.inspector_version
        return result

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "InspectReportPayload":
        """Reconstruct an :class:`InspectReportPayload` from a plain dict."""
        return cls(
            report_id=str(data["report_id"]),
            span_id=str(data["span_id"]),
            model=str(data["model"]),
            issues=[InspectIssueSummary.from_dict(i) for i in data.get("issues", [])],
            overall_severity=str(data["overall_severity"]),
            score=data.get("score"),
            inspector_version=data.get("inspector_version"),
        )


__all__: list[str] = [
    "InspectIssueSummary",
    "InspectReportPayload",
]
